Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 40

Metrics/AbcSize:
  Max: 25
